services:
  mongo:
    image: mongo:8.2.2-rc0-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  front:
    build:
      context: ./
      dockerfile: caddy.Dockerfile
    depends_on:
      - mongo
      - back
  back:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./apps/backend/.env
    depends_on:
      - mongo
