services:
  mongo:
    image: mongo:8.2.2-rc0-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  front:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - back
  back:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    env_file:
      - ./apps/backend/.env
    depends_on:
      - mongo
