services:
  mongo:
    image: mongo:8.2.2-rc0-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  front:
    image: ./apps/frontend/Dockerfile.prod
    depends_on:
      - mongo
      - back
  back:
    image: ./apps/backend/Dockerfile.prod
    depends_on:
      - mongo
